### ISSUE TITLE
Error in confint command with lr option

### ISSUE THREAD

**Issue by yushuf** [ekenah/transtat#2]
confint(unobs_tr, type = "lr") 

Error in uniroot(parm_d, treg$coefficients[parm] + c(-1.5, -0.5) * z *  : 
  f() values at end points not of opposite sign

The error is not too frequent but happens. I sent the input files through email

**Comment by ekenah** [comment]
This error occured when the lower LR confidence limit was outside the interval c(-1.5, -.5) * z * se(parm) or the upper LR confidence limit was outside c(.5, 1.5) * z * se(parm). I enabled the "expandInt" option in "uniroot" to allow the search interval to expand as needed. The error is fixed in version 0.2.3.

**Comment by yushuf** [comment]
Great! this is working now

Thanks
